sudo: required
services:
  - docker

before_install:
  - docker build -t victoria.pocladova/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true victoria.pocladova/docker-react  npm run test
 